[tasks.watch]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-c", "-x", "clippy", "-x", "test"]

[tasks.client]
install_crate = "trunk"
command = "trunk"
args = ["serve", "--open"]

[tasks.check]
command = "cargo"
args = ["check", "--all-features"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--all-features"]

[tasks.test]
command = "cargo"
args = ["test", "--all-features"]

[tasks.format]
command = "cargo"
args = ["fmt", "--all"]

# workflows

[tasks.check_all]
dependencies = ["check", "format", "lint"]

[tasks.submit]
dependencies = ["check", "format", "test", "lint"]

# aliases

[tasks.rc]
alias = "client"

[tasks.c]
alias = "check_all"

[tasks.s]
alias = "submit"
