[tasks.client]
install_crate = "trunk"
command = "trunk"
args = ["serve", "--open"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--all-features"]

[tasks.test]
command = "cargo"
args = ["test", "--all-features"]

[tasks.format]
command = "cargo"
args = ["fmt", "--all"]

[tasks.submit]
dependencies = ["format", "test", "lint"]